#pragma once

#include "filter_policy.h"
#include <cstddef>

namespace rocketdb {

class Cache;
class Comparator;
class Env;
class FilterPolicy;
class Logger;
class Snapshot;

// The enum describes which compression method is used to compress a block
enum CompressionType {
    kNoCompression = 0x0,
    kSnappyCompression = 0x1,
    kZstdCompression = 0x2,
};

struct Options {

    Options();

    // Comparator used to define the order of keys in table
    // Default uses lexicographic byte-wise ordering
    const Comparator* comparator;

    // If true, the database will be created if it is missing
    bool create_if_missing = false;

    // If true, an error is raised if the database already exists
    bool error_if_exists = false;

    // If true, the implementation will do aggressive checking of the data
    // that it is processing and will stop early if it detects any errors
    bool paranoid_checks = false;

    // Operating system environment encapsulation object
    Env* env;

    // Any internal process/error information generated by the db will be written to info_log if it is non_null
    Logger* info_log = nullptr;

    // The size of the memory write buffer, increasing it can improve wirte performance
    // But it will increase memory usage and take longer to recover after a crash
    size_t write_buffer_size = 4 * 1024 * 1024;

    // Number of open files that used by the DB
    int max_open_files = 1000;

    // If non_null, use the specified cache for blocks
    // If null, automatically create and use an 8 MB internal cache
    Cache* block_cache = nullptr;

    // Approximate size of user data packed per block
    size_t block_size = 4 * 1024;

    // Number of keys between restart points for delta encoding of keys
    int block_restart_interval = 16;

    // DB will wirte up to the amount of bytes to a file bufore switching to a new one
    size_t max_file_size = 2 * 1024 * 1024;

    // Compress blocks using the specified compression algorithm
    CompressionType compression = kSnappyCompression;

    // Compress level for zstd
    int zstd_compression_level = 1;

    // Default: currently false, but may become true later
    bool reuse_logs = false;

    // If non-null, use the specified filter policy to reduce disk reads
    const FilterPolicy* filter_policy = nullptr;
};

// Options that control read operations
struct ReadOptions {
    // If true, all data read from underlying starage will be verified against corresponding checksums
    bool verify_checksums = false;

    // If true, the data read for this iteration be cached in memory
    bool fill_cache = true;

    // If "snapshot" is non-null, read as of the supplied snapshot
    // If "snapshot" is null, use an implicit snapshot of the state at the beginning of this read operation.
    const Snapshot* snapshot = nullptr;
};

// Options that control write operations
struct WriteOptions {
    WriteOptions() = default;

    // If true, the write will be flushed from the operating system buffer cache
    // before the write is considered complete, writes will be slower
    //
    // If the flag si false, and the machine crashs, some recent writes may be lost
    bool sync = false;
};

}